### ISSUE TITLE
pypi packages are not installable on MSYS2

### ISSUE THREAD

**Issue by mimi89999** [pywinrt/pywinrt#44]
Hello,

Attempting to install a package in MSYS2 MINGW64 env from pypi fails:
```
$ SETUPTOOLS_USE_DISTUTILS=stdlib pip3 install winrt-Windows.UI.ViewManagement
...
      gcc -DNDEBUG -g -fwrapv -O3 -Wall -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -O3 -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -O3 -IC:/msys64/tmp/pip-build-env-rw297qt2/overlay/lib/python3.11/site-packages/winrt_sdk/cppwinrt -IC:/msys64/tmp/pip-build-env-rw297qt2/overlay/lib/python3.11/site-packages/winrt_sdk/pywinrt -IC:/msys64/mingw64/include/python3.11 -c _winrt.cpp -o build/temp.mingw_x86_64-3.11/_winrt.o /std:c++20 /permissive-
      gcc.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
```

This seems caused by the fact that MSYS2 GCC treats the args defined in `extra_compile_args` as paths:
```
Michel@DESKTOP-XXXXXXX MINGW64 ~
$ g++ test.cpp -o test /std:c++20
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find /std:c++20: No such file or directory
collect2.exe: error: ld returned 1 exit status
```

This could be solved by setting the args in the UNIX style (with a `-`) if MSYS2 is detected, however I don't know any nice way of detecting MSYS2 besides checking `os.environ`.

**Comment by dlech** [comment]
I think the "right" way to do this is override `build_ext` which allows us to see which compiler is being used.

https://stackoverflow.com/a/68349405/1976323

**Comment by dlech** [comment]
Can you try building with the latest `main` branch? Hopefully it is fixed, but I wouldn't be too surprised if it needs more compile flags.

**Comment by mimi89999** [comment]
Thanks for resolving that. Unfortunately there are other errors now 😞
