### ISSUE TITLE
How can I have "IInspectable" in python?

### ISSUE THREAD

**Issue by DobyChao** [pywinrt/pywinrt#48]
I'm trying to convert the following code from [this project](https://github.com/ArknightsAutoHelper/ArknightsAutoHelper/blob/master/util/d3dcapture.py) to pywinrt:
```
delegate = TypedEventHandler(rotypes.Windows.Graphics.Capture.GraphicsCaptureItem, IInspectable).delegate(self._closed_callback)
```
In the code above, `rotypes` is another implementation of Python bindings for winrt. I can't find a mapping for IInspectable in this repo's examples. How should I use it?

**Comment by dlech** [comment]
In PyWinRT 2.x, `IInspectable` is mapped to `winrt.system.Object`. Generally, you don't need to use it directly though (unless you just want it as a type hint) as all other runtime classes and interface projection types inherit from this type.

**Comment by DobyChao** [comment]
Based on what you're saying, I should simply translate it to:
```python
import winrt
import winrt.windows.graphics.capture

delegate = TypedEventHandler(winrt.windows.graphics.capture.GraphicsCaptureItem, winrt.system.Object).delegate(self._closed_callback)
```
Is this correct?

**Comment by dlech** [comment]
- With PyWinRT you don't have to create a delegate object. You just use a Python function directly for event handlers.
