### ISSUE TITLE
winrt-Windows.Foundation.Interop not available on PyPI

### ISSUE THREAD

**Issue by samschott** [pywinrt/pywinrt#53]
The interop module was clearly added in https://github.com/pywinrt/pywinrt/commit/d3b55413a2d102bc2cb864aae340fe4487b3a157 and is documented, but it does not seem to be available on PyPI.

Was this an oversight? Or is the documentation just a bit ahead of what is released?

**Comment by dlech** [comment]
It is building right now. If all goes well, it should by on PyPI in a few hours. (It didn't go well yesterday.)

**Comment by samschott** [comment]
In that case, fingers crossed. And congrats on the 2.0 release!

**Comment by dlech** [comment]
But this is a good reminder to fix the version added in the docs since there wasn't a beta 3 release.
