### ISSUE TITLE
Please add `windows.graphics.directx.direct3d11.interop` or a clean way to get an `IDirect3DDevice`

### ISSUE THREAD

**Issue by Avasam** [pywinrt/pywinrt#78]
I am mostly interested in https://learn.microsoft.com/en-us/windows/win32/api/windows.graphics.directx.direct3d11.interop/nf-windows-graphics-directx-direct3d11-interop-createdirect3d11devicefromdxgidevice

From the WGC API blog post (https://blogs.windows.com/windowsdeveloper/2019/09/16/new-ways-to-do-screen-capture/), `CreateDirect3D11DeviceFromDXGIDevice` is what's used to obtain an `IDirect3DDevice` to pass to `Direct3D11CaptureFramePool.Create`/`Direct3D11CaptureFramePool.CreateFreeThreaded`:
https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/blob/ee50e2ea137dcef7b82ba504eff7435e5ebf5294/dotnet/WPF/ScreenCapture/Composition.WindowsRuntimeHelpers/Direct3D11Helper.cs#L90C27-L90C63

This is also the recommended method from Microsoft's `IDirect3DDevice` Interface documentation https://learn.microsoft.com/en-us/uwp/api/windows.graphics.directx.direct3d11.idirect3ddevice?view=winrt-26100#remarks

I also see that `IDirect3DDevice` has a `_from` static method that returns a `IDirect3DDevice`. But it's unclear how I would use it.

Unless there's another way PyWinRT exposes to correctly get an `IDirect3DDevice`. For now, to work around this limitation, I am getting my device from `MediaCapture`, but this is finnicky as if the user doesn't have any capture media plugged in, no device can be obtained.

```py
import asyncio
from winrt.windows.media.capture import MediaCapture

def get_direct3d_device():
	media_capture = MediaCapture()
	
	async def init_mediacapture():
	        await media_capture.initialize_async()
	
	asyncio.run(init_mediacapture())
	direct_3d_device = (
	    media_capture.media_capture_settings
	    and media_capture.media_capture_settings.direct3_d11_device
	)
	
	if not direct_3d_device:
	    raise Exception("Unable to initialize a Direct3D Device. You need at least 1 capture device plugged in due to technical limitations")
	    
    return direct_3d_device
```

(this issue reflects this from the old repo: https://github.com/pywinrt/python-winsdk/issues/11)

**Comment by dlech** [comment]
Do you have example code (in any programming language) of how to create the `IDXGIDevice` instance?

**Comment by Avasam** [comment]
Sure, from my issue description, there's this Microsoft demo in CSharp: https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/blob/ee50e2ea137dcef7b82ba504eff7435e5ebf5294/dotnet/WPF/ScreenCapture/Composition.WindowsRuntimeHelpers/Direct3D11Helper.cs#L82-L99 (although they use SharpDX)

OBS (C++):
Starts from an `ID3D11Device`: https://github.com/obsproject/obs-studio/blob/93533d8e42d6b295b07eeaa9fccd7998e2b0f956/libobs-winrt/winrt-capture.cpp#L292-L294
(Btw you can see the same winrt calls we can do with pywinrt, and that I'm doing for Windows Graphics API on the lines right afterward)

D3DShot gets a `ID3D11Device` using ctypes (Python): https://github.com/SerpentAI/D3DShot/blob/4472120a21a1cb397d4f30d7a36af993e7544bc9/d3dshot/dll/d3d.py#L251-L272

During some of my research I found this project which seems to define an `IDXGIDevice` type using ctypes https://github.com/ynkdir/py-win32more/blob/fe83df6e06f95d7ccfbd96f0e6d1d87e335e9e75/win32more/Windows/Win32/Graphics/Dxgi/__init__.py#L841-L853

(I think I could bodge something together since, if D3DShot defined the struct for `IDXGIDevice`, then 
```
from d3dshot.display import Display
from d3dshot.dll.d3d import initialize_d3d_device, 
initialize_d3d_device(Display.discover_displays()[0].dxgi_adapter)[0].QueryInterface(IDXGIDevice)
```
Should get me a ref to a `IDXGIDevice` using ctypes/comtypes
https://learn.microsoft.com/en-us/windows/win32/api/dxgi/nn-dxgi-idxgidevice#remarks

**Comment by Avasam** [comment]
Thanks! I just tried it and it seems to be working great!
I simply vendored your sample for `D3D11CreateDevice`, trimmed it and added some type annotations.

**Comment by winstxnhdw** [comment]
Why can't `D3D11CreateDevice` be added to `.direct3d11.interop`?
